[package]
name = "fractals"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitflags = "2.10.0"
bytemuck = "1.24.0"
cgmath = "0.18.0"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
